# Generated by Django 5.2.17 on 2026-10-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sos_role',
            },
        ),
    ]
